# Generated by Django 4.1.2 on 2023-04-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruments',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
