# Generated by Django 4.1.2 on 2023-04-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_alter_instruments_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruments',
            name='price',
            field=models.FloatField(),
        ),
    ]
