# Generated by Django 4.1.2 on 2023-04-25 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0004_alter_instruments_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='img_for_instrument',
            options={'verbose_name': 'Фотографии муз инструментов', 'verbose_name_plural': 'Фотографии муз инстр'},
        ),
    ]
